### ISSUE TITLE
[Feedback]: The link for AML.T0040 "Discover ML Model Family" is incorrect.

### ISSUE THREAD

**Issue by donadonadona** [mitre-atlas/atlas-data#4]
## Feedback Summary
The link for "Discover ML Model Family" in the summary of AML.T0040 is incorrectly directed to "Discover ML Model Ontology".

## Proposal
Change the link to "Discover ML Model Family".

## Other links/references
https://atlas.mitre.org/techniques/AML.T0040

### What browsers were you on?

chrome

**Comment by lilyjw** [comment]
Appreciate it! Fixed in the latest release.
